### PR TITLE
Gmd multigas

### PR DESCRIPTION
**Pull request by richardcode**
Creating pull request to merge Chris' multigas boxes into the master code.

### CODE REVIEW

**Comment by richardcode** [comment]
@chrisroadmap what is the `tcr_dbl` parameter for? Surely TCR is always defined around year 70 of 1%/yr integration?

**Comment by richardcode** [comment]
@chrisroadmap after a first detailed read through this looks pretty good to me and very nicely separated. Nice job! Will have a more detailed play with the code this afternoon. Looking at the code it looks to me as though if some emissions are set to zeros then there would be no forcing from them so different species could essentially be left out/and extra forcing specified instead?

**Comment by chrisroadmap** [comment]
@richardcode In my simulations I use log(2) / log (1.01) ~= 69.7 years as the time to a doubling of CO2 concentrations, which is the limit of a compound 1% yearly increase. I don't think there is a strict definition anywhere that says 70, but I am aware that this is standard practice. For backwards compatibility I have left 70 as the default value.

**Comment by chrisroadmap** [comment]
@richardcode There are some emissions categories that have more than one forcing dependent on them, e.g. NOx affects aerosol, contrail and tropospheric ozone forcing. If you wanted to remove a forcing from a specific category you could set its entry in the 13-element `scale` array to zero. Perhaps I need some better documentation as to which emissions, concentration and forcing index correspond to which species.

**Comment by richardcode** [comment]
@chrisroadmap thanks. Yes, makes sense. I think for the complex models it is the average of the 20 years surrounding year 70 so probably makes sense to have as default. 

Yes, I see the scale parameter now. Would definitely make sense to have an easier to remember linkage between positions in the arrays and species in the future but don't think this should stop us from merging with the master at this point. Might be good to use a pandas dataframe object for the emissions and forcing arrays etc as they decent implementations of named columns etc?

**Comment by chrisroadmap** [comment]
@richardcode Good idea - I'll add this to my wishlist - and it'll be fairly near the top as quite trivial to implement.

**Comment by richardcode** [comment]
@chrisroadmap @znicholls Going to action this merge now maintaining the commit history so that this is good for Chris' GMD submission. We can continue the review on that branch as the GMD process is likely to be quite slow according to Chris' expectations.

**Comment by znicholls** [comment]
Sorry for silence on this, all looks good. I hope to be able to provide
more useful input in the future.

**Pull request merged**
